# Pandas

Made from the Numpy as the Base, so it is faster

It is all about data and making changes in the data

In [1]:
import pandas as pd

In [2]:
print(pd.__version__) # To know the current version of the panda

1.0.5


## Series

In [3]:
A = pd.Series([2,3,4,5],index=['a','b','c','d']) 
#series handles one dimensonal arrays and idex doesnot necessarily have to be a string
A.values

array([2, 3, 4, 5], dtype=int64)

In [4]:
type(A.values)

numpy.ndarray

In [5]:
type(A)

pandas.core.series.Series

In [6]:
A.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [7]:
A['a']

2

In [8]:
A['a':'c'] # Slicing by using : in which the slicing will also include c

a    2
b    3
c    4
dtype: int64

### Creating Dictionaries by using Series

In [9]:
grades_dict = {'A':1,'B':2,'C':3,'D':4}
grades = pd.Series(grades_dict)
print(grades)

A    1
B    2
C    3
D    4
dtype: int64


In [10]:
grades.values

array([1, 2, 3, 4], dtype=int64)

In [11]:
grades.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [12]:
grades['A']

1

In [13]:
grades['A':'C'] # Special slicing by using index

A    1
B    2
C    3
dtype: int64

In [14]:
grades[0:2] # Normal slicing where grades[2] is not given

A    1
B    2
dtype: int64

## DataFrames

In [15]:
A

a    2
b    3
c    4
d    5
dtype: int64

In [16]:
grades

A    1
B    2
C    3
D    4
dtype: int64

In [17]:
D = pd.DataFrame({'ABCD':A,'GradesA':grades})

In [18]:
D

ABCD  GradesA
A   NaN      1.0
B   NaN      2.0
C   NaN      3.0
D   NaN      4.0
a   2.0      NaN
b   3.0      NaN
c   4.0      NaN
d   5.0      NaN

In [19]:
D.T # Transpose value of Dataframe

A    B    C    D    a    b    c    d
ABCD     NaN  NaN  NaN  NaN  2.0  3.0  4.0  5.0
GradesA  1.0  2.0  3.0  4.0  NaN  NaN  NaN  NaN

In [20]:
print(D) #It is not a colourful value as it is a python file

   ABCD  GradesA
A   NaN      1.0
B   NaN      2.0
C   NaN      3.0
D   NaN      4.0
a   2.0      NaN
b   3.0      NaN
c   4.0      NaN
d   5.0      NaN


In [21]:
D.values # To get only the values in the form of the matrix

array([[nan,  1.],
       [nan,  2.],
       [nan,  3.],
       [nan,  4.],
       [ 2., nan],
       [ 3., nan],
       [ 4., nan],
       [ 5., nan]])

In [22]:
D.values[4,0]

2.0

In [23]:
D.columns

Index(['ABCD', 'GradesA'], dtype='object')

In [24]:
D['NewColumn'] = 100*(D['ABCD']/90)  
# Inserting columns by using the same functions as dictionary 

In [25]:
del D['GradesA'] #df.drop['Put the index numbers GradesA']

In [26]:
D

ABCD  NewColumn
A   NaN        NaN
B   NaN        NaN
C   NaN        NaN
D   NaN        NaN
a   2.0   2.222222
b   3.0   3.333333
c   4.0   4.444444
d   5.0   5.555556

In [27]:
E = D[D['ABCD']>3]

In [28]:
E

ABCD  NewColumn
c   4.0   4.444444
d   5.0   5.555556

#### The NaN represents the empty value or none value

In [29]:
D.fillna(0) #Filling NaN value by 0

ABCD  NewColumn
A   0.0   0.000000
B   0.0   0.000000
C   0.0   0.000000
D   0.0   0.000000
a   2.0   2.222222
b   3.0   3.333333
c   4.0   4.444444
d   5.0   5.555556

In [30]:
# A.dropna drops all the missing values or NaN values

### Indexing using iloc and loc instead of the normal confusing values of D[1], D[1,3]

Differentiating between explicit (**loc**) index and implicit (**iloc**) index

In [31]:
A

a    2
b    3
c    4
d    5
dtype: int64

In [32]:
A['b'] # Explicit index (If it was number it would also give explicit index instead of implicit index)

3

In [33]:
A[1:3] # Implicit index 

b    3
c    4
dtype: int64

In [34]:
# A.loc is used to make explicit index and A.iloc to make implicit index

In [35]:
# Explicit - dictionary value     Implicit - normal value on the list which can be assesed by D[1],D[2],D[2:3] etc.

## Pandas Data Sets (.csv files)

We use .csv files to record data sets and use python to change it